#!/usr/bin/env bash
set -euo pipefail
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
UPLOAD_FILE=

usage() {
  echo "$0 <artist>" >&2
  exit 1
}

# shellcheck source=/dev/null
source "$ROOT_DIR/utils/source.sh"
source_modules \
  utils/db.sh \
  utils/profile.sh \
  utils/image.sh

main() {
  local artist
  [ "$#" -eq 1 ] || usage
  artist=$1
  profile_prepare
  UPLOAD_FILE=$(mktemp "$ARTS_STATE_DIR/.upload.XXXXXX")
  trap 'rm -f "$UPLOAD_FILE"' EXIT HUP INT TERM
  cat >"$UPLOAD_FILE"
  image_add "$artist" "$UPLOAD_FILE"
}

main "$@"
