#!/usr/bin/env bash
set -euo pipefail
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

usage() {
  echo "$0 <id...>" >&2
  exit 1
}

# shellcheck source=/dev/null
source "$ROOT_DIR/utils/source.sh"
source_modules \
  utils/db.sh \
  utils/profile.sh \
  utils/object.sh \
  utils/image.sh \
  utils/sequence.sh

main() {
  local id
  [ "$#" -ge 1 ] || usage
  profile_prepare
  for id in "$@"; do
    case "$(object_type "$id")" in
      image) image_remove "$id" ;;
      sequence) sequence_remove "$id" ;;
    esac
  done
}

main "$@"
