#!/usr/bin/env bash
set -euo pipefail
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

usage() {
  echo "$0 [subject[:source]]" >&2
  exit 1
}

# shellcheck source=/dev/null
source "$ROOT_DIR/utils/source.sh"
source_modules \
  utils/state.sh \
  utils/image.sh \
  utils/location.sh \
  utils/display.sh

main() {
  local targets
  local arg
  local status
  local -a location_args
  local -a result_targets
  location_args=()
  result_targets=()
  case "$#" in
    0) ;;
    1)
      case "$1" in
        -*) usage ;;
      esac
      location_args=("$1")
      ;;
    2)
      [ "$1" = -- ] || usage
      location_args=("$2")
      ;;
    *) usage ;;
  esac
  state_prepare
  if [ -t 0 ] && [ -t 1 ]; then
    display_cursor_hide
    trap display_cursor_show EXIT
  fi
  # shellcheck disable=SC2034
  DISPLAY_SELECTED=0
  while :; do
    result_targets=()
    targets=$(location_search "${location_args[@]}")
    while IFS= read -r arg; do
      [ -n "$arg" ] && result_targets+=("$arg")
    done <<<"$targets"
    if [ ! -t 0 ] || [ ! -t 1 ]; then
      if [ "${#result_targets[@]}" -gt 0 ]; then
        printf '%s\n' "${result_targets[@]}"
      fi
      return 0
    fi
    if display_browser "${result_targets[@]}"; then
      return 0
    else
      status=$?
    fi
    [ "$status" -eq 10 ] || return "$status"
  done
}

main "$@"
